FROM osrf/ros:kinetic-desktop-full

RUN	apt update \
	&& apt install -y mlocate \
	&& apt install -y vim \
	&& apt install -y less \
   	&& apt install -y ros-kinetic-rosbridge-suite \
	&& apt install ros-kinetic-roswww \
	&& apt install -y ros-kinetic-web-video-server \
	#&& mkdir -p ~/catkin_ws/src \
	#&& cd ~/catkin_ws/ \
	#&& catkin_make \
	#&& source devel/setup.bash 	